describe('Main spec', () => {
  const username = ''
  const password = ''

  beforeEach(() => {
    cy.visit('https://www.njuskalo.hr/')
    cy.get('#didomi-notice-agree-button')
      .click()
  })

  it('Login and logout', () => {
    cy.contains(/prijava/i)
      .should('be.visible')
      .click()
    cy.get('#login_username')
      .type(`${username}`)
      .should('have.value', `${username}`)
    cy.get('#login_password')
      .type(`${password}`)
      .should('have.value', `${password}`)
    cy.get('button')
      .contains(/prijavi se/i)
      .click()
    cy.get('span')
      .contains(`${username}`)
      .should('be.visible')
    cy.contains(/odjava/i)
      .should('be.visible')
      .click()
    cy.contains(/prijava/i)
      .should('be.visible')
  })

  it('Search for "Audi A4"', () => {
    const keyword = 'Audi A4'
    const max_price = '15000'
    cy.contains(/prijava/i)
      .should('be.visible')
      .click()
    cy.get('#login_username')
      .type(`${username}`)
      .should('have.value', `${username}`)
    cy.get('#login_password')
      .type(`${password}`)
      .should('have.value', `${password}`)
    cy.get('button')
      .contains(/prijavi se/i)
      .click()
    cy.get('span')
      .contains(`${username}`)
      .should('be.visible')
    cy.get('#keywords')
      .type(`${keyword}{enter}`)
      .should('have.value', `${keyword}`)
    cy.get('#price[max]')
      .type(`${max_price}`)
      .should('have.value', `${max_price}`)
    cy.get('button')
      .contains(/pronjuškaj/i)
      .click()
    cy.contains(/odjava/i)
      .should('be.visible')
      .click()
    cy.contains(/prijava/i)
      .should('be.visible')
  })

  it('Search for id "1349039"', () => {
    const id = '1349039'
    cy.contains(/prijava/i)
      .should('be.visible')
      .click()
    cy.get('#login_username')
      .type(`${username}`)
      .should('have.value', `${username}`)
    cy.get('#login_password')
      .type(`${password}`)
      .should('have.value', `${password}`)
    cy.get('button')
      .contains(/prijavi se/i)
      .click()
    cy.get('span')
      .contains(`${username}`)
      .should('be.visible')
    cy.get('#keywords')
      .type(`${id}{enter}`)
      .should('have.value', `${id}`)
    cy.contains(/odjava/i)
      .should('be.visible')
      .click()
    cy.contains(/prijava/i)
      .should('be.visible')
  })
})